import type { Metadata } from 'next'
import './globals.css'
import { ThemeProvider } from '@/components/providers/theme-provider'

import localFont from '@next/font/local'

const roobert = localFont({
  src: [
    {
      path: '../../public/fonts/RoobertLight.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/RoobertRegular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/RoobertMedium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/RoobertSemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/fonts/RoobertBold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/RoobertHeavy.ttf',
      weight: '800',
      style: 'normal',
    },
  ],
  variable: '--font-roobert',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body className={roobert.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
          storageKey="ivgnod-theme"
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
